### PR TITLE
Fix i18n issue making the app not start

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by aleixpol** [comment]
Why is it only needed in flatpak?

**Comment by tsdgeos** [comment]
Because we build in debug and thus the warning is an assert

**Comment by Erick555** [comment]
@tsdgeos I noticed this while reading kde runtime build logs. I think this is notable mistake and  needs fixing in kde runtime.

**Comment by Erick555** [comment]
@tsdgeos @aleixpol generally there are more issues with how frameworks are being build right now, for example `-DENABLE_TESTING=OFF` is passed for every build while it should be `-DBUILD_TESTING=OFF` which results in all test being build for every module...

**Pull request merged**
