### PR TITLE
Next update

### PR DESCRIPTION
**Pull request by ElXreno**
**Updates:**
* Marble: Updated tag
* libksane: Updated tag
* lensfun: Updated repo commit (for db)
* ImageMagisk: Updated to version 7.0.10-29
* Jasper: Updated to version 2.0.20
* Sane Backends: Updated to version 1.0.31
* net-snmp: Updated to version 5.9

**Misc:**
* Boost: Updated build commands
* Sane Backends: Updated config opts ([reason](https://gitlab.com/sane-project/backends/-/releases/1.0.31#build))

### CODE REVIEW

**Comment by tsdgeos** [comment]
What does digikam use poppler for?

**Comment by cgilles** [comment]
digiKam do not use poppler as dependency, by certainly KF5 framework.

This is the list of digiKam dependencies:

https://www.digikam.org/api/index.html#externaldeps

**Comment by Erick555** [comment]
The dependency chain goes like `digikam` < `libksane` < `sane` < `poppler`.

**Comment by tsdgeos** [comment]
Fair enough :)

**Pull request merged**
