### PR TITLE
Update modules & Build more modules for sane backends

### PR DESCRIPTION
**Pull request by ElXreno**
If someone can check additional modules for sane-backends, please, check it and write here about results. I only checked escl backend and all works fine.

### CODE REVIEW

**Comment by ElXreno** [comment]
@cgilles Before I push this into production, I'd like to ask you a question. Why isn't all languages available in [the source archive](https://download.kde.org/unstable/digikam/digikam-7.0.0-rc.tar.xz)?

**Comment by cgilles** [comment]
Languages must be included in archive for GUI translations. There is a script running before the packaging which extract .po files and check if file can be compiled in .mo target. if not, translations file is dropped from the tarball. This is due to transition state of the application (beta) where translators typically finalize i18n just before the final release.

Translation is a huge job and sometime .po file and not finalized and not compilable.

**Comment by ElXreno** [comment]
@cgilles I found [a problem](https://invent.kde.org/graphics/digikam/-/blob/master/project/release/fetch_l10n_po.rb#L62) in your script. It's just an old path to translation. Maybe someone rename this directory without notification about it.

Old path: `svn://anonsvn.kde.org/home/kde/#{branch}/l10n-kf5/#{lang}/messages/extragear-graphics/#{part}.po`
New path (I think): `svn://anonsvn.kde.org/home/kde/#{branch}/l10n-kf5/#{lang}/messages/digikam/#{part}.po`

**Comment by ElXreno** [comment]
I send a pull request. Please review them and accept or close it.
https://invent.kde.org/graphics/digikam/-/merge_requests/28

**Pull request merged**
