### PR TITLE
Fix HEIF decoding & add BMFF support in exiv2

### LINKED ISSUE #40: heif decoding in version 7.7.0 not supported
SUMMARY
The decoding of heif files fails in version 7.7.0

STEPS TO REPRODUCE
1. Add the example.heic or example.avif (from the libheif git repository, directory "examples") to the collection.

OBSERVED RESULT
They are recognized but not decoded (no thumbnail is shown, the image preview does not work).

ADDITIONAL INFORMATION
I'd guess libde265 is missing:
A) There is no libde265 module in the json.
B) The latest buildlog states at line 100579: "HEIF decoder, libde265: not found" (and similar at other lines).
C) According to issue #32 it should be added? Note that it adds libheif and a duplicate libx265 but no libde265.
D) The appimage supports decoding of heif files, thus I guess the error is not at libheif itself.

Thanks!

### PR DESCRIPTION
**Pull request by ElXreno**
Partially fixes #40 issue, but AVIF decoding still fails.
Also, exiv2 now includes support for BMFF (this enables AVIF and HEIF/HEIC containers support).

### CODE REVIEW

**Comment by hfiguiere** [comment]
> Partially fixes #40 issue, but AVIF decoding still fails. 

I think libheif wants an avif decoder for that.

**Comment by ElXreno** [comment]
> I think libheif wants an avif decoder for that.

There are lines in the [latest build log](https://buildbot.flathub.org/#/builders/48/builds/12085)([raw](https://buildbot.flathub.org/api/v2/logs/3996153/raw)) during the `heif` build that `aom` encoder and decoder is found:
```
AVIF encoder, aom: found
AVIF decoder, aom: found
```
I tried to add `libavif` and `aom` as modules in `libheif`, it does not fix the problem.

**Comment by pkrause1980** [comment]
For what I understand from the issue and the digikam developers, building kimageformats with proper dependencies (libaom etc) should fix the loading of avif files.

However, kimageformats seems to be part of the kde-runtime (it is in the manifest of it).

I'm not sure, but does not digikam can use Imagemagick for decoding images? Imagemagick should decode avif files if libheif (with libaom etc) is build before it. That would be a workaround.

Sorry, but I'm very slow and will likely not be able to test this very soon.

**Comment by cgilles** [comment]
ImageMagick is a 3rd party codec collection to open image. KImageFormat is the prefered. If it do not work IM is a fail back solution.

IM has some problems as it slowly, and crash with corrupted files (not exceptions).

For the AppImage bundle that we provide, KImageFormat is recompiled with AOM AVIf support.

**Comment by pkrause1980** [comment]
> > I think libheif wants an avif decoder for that.
> 
> There are lines in the [latest build log](https://buildbot.flathub.org/#/builders/48/builds/12085)([raw](https://buildbot.flathub.org/api/v2/logs/3996153/raw)) during the `heif` build that `aom` encoder and decoder is found:
> 
> ```
> AVIF encoder, aom: found
> AVIF decoder, aom: found
> ```
> 
> I tried to add `libavif` and `aom` as modules in `libheif`, it does not fix the problem.

Regarding libaom and libdav1d:
These are already provided by the runtime, so there should be no need to add them as modules.

**Comment by pkrause1980** [comment]
Regarding loading avif-files via ImageMagick:

I made a build with libheif before ImageMagick, and it does not work for me.

First:
ImageMagick is not used by Digikam, I tried the flathub version too and opened a separate issue, c.f. #42.

Second, however that could be just misleading output:
ImageMagick does not find libheif at compile time: "checking for libheif >= 1.4.0... no".
Even though libheif is clearly there (pkg-config finds it).
Imagemagick finds libheif if the manifest is stripped down to just the runtime, libde265 and libheif.
Thus the error is somehow strangely introduced with io.qt.qtwebengine.BaseApp, org.freedesktop.Platform.ffmpeg-full, or some module build before libheif.

**Comment by pkrause1980** [comment]
> Regarding loading avif-files via ImageMagick:
> 
> I made a build with libheif before ImageMagick, and it does not work for me.
> 
> First: ImageMagick is not used by Digikam, I tried the flathub version too and opened a separate issue, c.f. #42.
> 
> Second, however that could be just misleading output: ImageMagick does not find libheif at compile time: "checking for libheif >= 1.4.0... no". Even though libheif is clearly there (pkg-config finds it). Imagemagick finds libheif if the manifest is stripped down to just the runtime, libde265 and libheif. Thus the error is somehow strangely introduced with io.qt.qtwebengine.BaseApp, org.freedesktop.Platform.ffmpeg-full, or some module build before libheif.

1) Fixed, at least for me, by pull-request #43.

2) Fixed, at least for me, by this pull request at libde265:
https://github.com/strukturag/libde265/pull/333
Sorry, I made a misleading comment. I removed the "buildsystem" node and forgot about it.
Therefore, and as major distribution seem to build equivalently, that should be a fix too.

In total, Digikam loads avif, and other, files via ImageMagick with these fixes, at least for me.

**Review by Stankisha — APPROVED** [review]

**Comment by pkrause1980** [comment]
> > Regarding loading avif-files via ImageMagick:
> > I made a build with libheif before ImageMagick, and it does not work for me.
> > First: ImageMagick is not used by Digikam, I tried the flathub version too and opened a separate issue, c.f. #42.
> > Second, however that could be just misleading output: ImageMagick does not find libheif at compile time: "checking for libheif >= 1.4.0... no". Even though libheif is clearly there (pkg-config finds it). Imagemagick finds libheif if the manifest is stripped down to just the runtime, libde265 and libheif. Thus the error is somehow strangely introduced with io.qt.qtwebengine.BaseApp, org.freedesktop.Platform.ffmpeg-full, or some module build before libheif.
> 
>     1. Fixed, at least for me, by pull-request [Do not delete libtool files of ImageMagick coders #43](https://github.com/flathub/org.kde.digikam/pull/43).
> 
>     2. Fixed, at least for me, by this pull request at libde265:
>        [Export pkg-config file in CMake builds strukturag/libde265#333](https://github.com/strukturag/libde265/pull/333)
>        Sorry, I made a misleading comment. I removed the "buildsystem" node and forgot about it.
>        Therefore, and as major distribution seem to build equivalently, that should be a fix too.
> 
> 
> In total, Digikam loads avif, and other, files via ImageMagick with these fixes, at least for me.

Regarding avif files, novomesk made this pull-request to the kde-runtime, which should enable decoding via kimageformat:
https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/104

It is merged, but appears to be not shipped via flathub and I failed to gather further information (does not seem to be build at binary-factory.kde.org, etc, etc).
In case somebody can help?

**Comment by Erick555** [comment]
libavif from kde runtime can be only used for kimageformats. If you want to use libavif through something else like imagemagick then you need to build your own libavif.

**Comment by pkrause1980** [comment]
The kde runtime at flathub now supports avif decoding via kimageformats, and thus also by digikam.

I suggest to merge the two commits from ElXreno and close the corresponding issue (#40) as it is fixed then.

Thanks!

**Pull request merged**
