### PR TITLE
Update digiKam & their dependencies

### LINKED ISSUE #22: Will digikam flatpak be updated to 7.3?
Will digikam flatpak be updated to 7.3? It seems to be on 7.2

### PR DESCRIPTION
**Pull request by ElXreno**
Fixes #22

### CODE REVIEW

**Comment by Erick555** [comment]
Note that appdata wasn't updated for release [again](https://invent.kde.org/graphics/digikam/-/blob/v7.3.0/core/app/main/org.kde.digikam.appdata.xml#L665). I think it missed update for every single of past releases so maybe either maintain a local copy of appdata file or tell upstream about need of making appdata update part of release process.

**Comment by tsdgeos** [comment]
@ElXreno do you want to have a look at the appdata thing now or merge this and have a look at the appdata later?

**Comment by ElXreno** [comment]
@tsdgeos I don't think it's worth merging this PR yet, until I add appdata. I'll do it tonight, I don't have any free time right now.

**Comment by ElXreno** [comment]
Apparently, the basic functionality works fine.

**Pull request merged**
